export const DEFAULT_SITE_CONTENT = {
  heroEyebrow: "RESTLESS COFFEE & EATERY",
  heroTitleLine1: "Take a pause.",
  heroTitleLine2: "Stay a while.",
  heroDescription: "Kopi, comfort food, dan sudut tenang di tengah Yogyakarta. Datang untuk secangkir, tinggal untuk suasananya.",
  heroPrimaryButton: "Lihat menu",
  heroSecondaryButton: "Temukan kami",
  aboutKicker: "01 / ABOUT",
  aboutTitleLine1: "Ruang untuk bernapas,",
  aboutTitleLine2: "rasa untuk diingat.",
  aboutDescription: "Di Restless, kami percaya jeda yang baik dimulai dari meja yang nyaman. Nikmati sarapan, makanan hangat, dan racikan kopi yang dibuat untuk menemani hari—pelan-pelan.",
  openingLabel: "OPEN DAILY",
  openingHours: "09.00 — 23.00",
  address: "Jl. Gayam No. 3, Yogyakarta",
  menuKicker: "02 / OUR MENU",
  menuTitleLine1: "What are you",
  menuTitleLine2: "in the mood for?",
  menuDescription: "Dari sarapan santai sampai kopi sore, temukan pilihan yang pas untuk jedamu.",
  visitKicker: "03 / FIND YOUR PAUSE",
  visitTitleLine1: "See you at",
  visitTitleLine2: "Restless.",
  reservationLabel: "Reservasi",
  reservationCaption: "Book your table",
  locationLabel: "Lokasi",
  locationCaption: "Jl. Gayam No. 3",
  orderLabel: "Pesan Online",
  orderCaption: "GrabFood & GoFood",
  deliveryLabel: "Pesan dari rumah",
  footerTagline: "Come and relax ✦",
  whatsappUrl: "https://wa.me/6287866885757",
  mapsUrl: "https://maps.app.goo.gl/S7FGFkZqBssgReYw5?g_st=ic",
  grabUrl: "https://r.grab.com/g/6-20240317_203531_C7E4957027A948B29E7699639ABB8166_MEXMPS-6-C6DYGTMXN6JYKA",
  gofoodUrl: "https://gofood.link/a/JqyUbMo",
  instagramUrl: "https://instagram.com/restless.coffee",
};

export type SiteContent = Record<keyof typeof DEFAULT_SITE_CONTENT, string>;

export const CONTENT_LIMITS: Record<keyof SiteContent, number> = {
  heroEyebrow: 80, heroTitleLine1: 80, heroTitleLine2: 80, heroDescription: 320, heroPrimaryButton: 40, heroSecondaryButton: 40,
  aboutKicker: 40, aboutTitleLine1: 100, aboutTitleLine2: 100, aboutDescription: 500, openingLabel: 40, openingHours: 40, address: 180,
  menuKicker: 40, menuTitleLine1: 100, menuTitleLine2: 100, menuDescription: 320,
  visitKicker: 50, visitTitleLine1: 100, visitTitleLine2: 100,
  reservationLabel: 50, reservationCaption: 100, locationLabel: 50, locationCaption: 120, orderLabel: 50, orderCaption: 120,
  deliveryLabel: 80, footerTagline: 100, whatsappUrl: 500, mapsUrl: 500, grabUrl: 500, gofoodUrl: 500, instagramUrl: 500,
};
